---
- name: ec2 instance using ansible
- hosts: manage1
  gather_facts: false
  tasks:
    - name: Create EC2 instance
      ec2_instance:
        instance_type: t2.micro
        security_groups: default  
        image_id: ami-0f8ca728008ff5af4
        region: ap-south-1
        key_name: UBUNTU2
        tags:
          Name: my-instance
          Environment: production
        wait: yes
      register: ec2_instance
    - name: Print public IP address
      debug:
        var: ec2_instance.instances[0].public_ip_address
    - name: Print private IP address
      debug:
        var: ec2_instance.instances[0].private_ip_address
      
