# create a file name as variable.yml
# define variable and there value inside variable.yml like this
# package: nginx
# service: sshd
# run the playbook ansible-playbook var-playbook.yml -k


---
 - name: installing web-server            # name of play 
   hosts: manage1                         # name of host group name
   vars_files:                            # calling variable.yml inside playbook
         - variable.yml
   become: true                           # defining become
   tasks:                                 
        - name: installing {{package}} web_server     # name of 1st task
          apt:                            # apt module to install any package
             name: "{{package}}"                  # name of package to install
             state: present               # state is present for package

        - name: copy webdata              # name of 2nd task
          copy:                           # copy module to copy data from src to dest
            src: index.html               # source of file to copy
            dest: /var/www/html           # destination of file to copy
         
        - name: start {{service}} service             # name of 3rd task
          service:                        # using service module to start the service 
            name: "{{service}}"                   # name of the service to start
            state: started                # state of the service



